// Generated by CoffeeScript 2.7.0
(function() {
  var DEFAULT_ENTRIES, SuperDry, entries, merge, omit, sd;

  ({SuperDry} = require('superdry'));

  ({merge, omit} = require('lodash'));

  sd = new SuperDry();

  DEFAULT_ENTRIES = {
    1506184685750: {
      description: 'buy milk'
    },
    1506184685751: {
      description: 'buy cheese',
      completed: true
    }
  };

  entries = Object.assign({}, DEFAULT_ENTRIES);

  sd.get('list', '/entries', function() {
    return Object.entries(entries).map(function([id, entry]) {
      return merge({}, entry, {id});
    });
  });

  sd.post('create', '/entries', function(req) {
    var id;
    ({id} = req.body);
    entries[id] = omit(req.body, 'id');
    return {
      status: 'ok'
    };
  });

  sd.patch('update', '/entry/:id', function(req) {
    entries[req.params.id] = req.body;
    return {
      status: 'ok'
    };
  });

  sd.delete('remove', '/entry/:id', function(req) {
    delete entries[req.params.id];
    return {
      status: 'ok'
    };
  });

  module.exports = {
    setupRoutes: function(app) {
      return sd.setupRoutes(app);
    },
    client: sd.setupDriver()
  };

}).call(this);
