// Generated by CoffeeScript 2.7.0
import React from 'react';

import {
  render
} from 'react-dom';

import TodoMvc from './TodoMvc';

render(React.createElement(TodoMvc), document.getElementById('root'));
