// Generated by CoffeeScript 2.7.0
var Entry, EntryList, Footer, Input, Todo, TodoStore;

import {
  every,
  find,
  filter,
  isEmpty,
  pick,
  remove
} from 'lodash';

import {
  Component,
  Store
} from 'superdry';

import theme from './theme';

import api from './apiDriver';

// Stores
Entry = class Entry extends Store {
  setup(load = {}) {
    return {
      description: (load != null ? load.description : void 0) || '',
      completed: (load != null ? load.completed : void 0) || false,
      editing: false,
      id: (load != null ? load.id : void 0) || Date.now()
    };
  }

  onUpdate() {
    if (!this.editing) {
      return api.patch(this.id, this.json());
    }
  }

};

TodoStore = class TodoStore extends Store {
  setup() {
    return {
      entries: [],
      visibility: 'All',
      input: '',
      visibleEntries: function() {
        switch (this.visibility) {
          case 'Completed':
            return this.completedEntries;
          case 'Active':
            return this.incompletedEntries;
          default:
            return this.entries;
        }
      },
      completedEntries: function() {
        return filter(this.entries, 'completed');
      },
      incompletedEntries: function() {
        return filter(this.entries, ['completed', false]);
      },
      entriesLeft: function() {
        var count;
        count = this.incompletedEntries.length;
        switch (count) {
          case 0:
            return '';
          case 1:
            return '1 item left';
        }
      }
    };
  }

  async load() {
    var entries, i, len, obj, results;
    entries = (await api.list());
    if (!entries) {
      return;
    }
    results = [];
    for (i = 0, len = entries.length; i < len; i++) {
      obj = entries[i];
      results.push(this.entries.push(new Entry(obj)));
    }
    return results;
  }

  onEntriesCreate(entry) {
    return api.create(entry);
  }

  onEntriesDelete(entry) {
    return api.delete(entry.id);
  }

};

export var $ = new TodoStore();

// Components
Input = Component(function() {
  var add, updateField;
  updateField = function(input) {
    return $.input = input;
  };
  add = function() {
    $.entries.push(new Entry({
      description: $.input
    }));
    return $.input = '';
  };
  return theme.apply(function(t) {
    return t.newTodo({
      placeholder: 'What needs to be done?',
      value: $.input,
      name: 'newTodo',
      onInput: updateField,
      onEnter: add
    });
  });
});

EntryList = Component(function() {
  var _entry, check, checkAll, deleteEntry, edit, update;
  _entry = function(id) {
    return find($.entries, {
      id: id
    });
  };
  checkAll = function() {
    var entry, i, len, ref, results;
    ref = $.entries;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      entry = ref[i];
      results.push(entry.completed = true);
    }
    return results;
  };
  check = function(id) {
    var entry;
    entry = _entry(id);
    return entry.completed = !entry.completed;
  };
  edit = function(id, isEditing = true) {
    var entry;
    entry = _entry(id);
    return entry.editing = isEditing;
  };
  update = function(id, text) {
    return _entry(id).description = text;
  };
  deleteEntry = function(id) {
    return remove($.entries, function(entry) {
      return entry.id === id;
    });
  };
  return theme.apply(function(t) {
    return t.with('main', {
      empty: isEmpty($.entries)
    })(function() {
      t.toggle({
        name: 'toggle',
        checked: every($.entries, 'completed'),
        onChange: checkAll
      });
      t.toggleLabel({
        for: 'toggle'
      }, 'Mark all as complete');
      return t.list(function() {
        return $.visibleEntries.forEach(function(entry) {
          return t.with('task', pick(entry, 'editing'))(function() {
            if (entry.editing) {
              return t.taskEdit({
                value: entry.description,
                id: entry.id,
                onInput: function(text) {
                  return update(entry.id, text);
                },
                onBlur: function() {
                  return edit(entry.id, false);
                },
                onEnter: function() {
                  return edit(entry.id, false);
                }
              });
            } else {
              t.taskToggle({
                checked: entry.completed,
                onChange: function() {
                  return check(entry.id);
                }
              });
              t.with('entryLabel', pick(entry, 'completed'))({
                onDoubleClick: function() {
                  return edit(entry.id);
                }
              }, entry.description);
              return t.destroyBtn({
                onClick: function() {
                  return deleteEntry(entry.id);
                }
              });
            }
          });
        });
      });
    });
  });
});

Footer = Component(function() {
  var changeVisibility, clear;
  changeVisibility = function(visibility) {
    return $.visibility = visibility;
  };
  clear = function() {
    return remove($.entries, 'completed');
  };
  return theme.apply(function(t) {
    if (!isEmpty($.entries)) {
      return t.footer(function() {
        var completions;
        t.counter($.entriesLeft);
        t.filters(function() {
          return ['All', 'Active', 'Completed'].forEach(function(visibility) {
            var current, opts;
            opts = {
              onClick: function() {
                return changeVisibility(visibility);
              }
            };
            current = visibility === $.visibility;
            return t.with('filter', {
              current: current
            })(opts, visibility);
          });
        });
        completions = $.completedEntries.length;
        if (completions > 0) {
          return t.clearBtn({
            onClick: clear
          }, `Clear completed (${completions})`);
        }
      });
    }
  });
});

Todo = Component(function() {
  return theme.apply(function(t) {
    return t.wrapper(function() {
      t.app(function() {
        t.header('todos');
        t.com(Input);
        t.com(EntryList);
        return t.com(Footer);
      });
      return t.info(function() {
        t.infoLine('Double-click to edit a todo');
        t.infoLine(function() {
          t.build('span', 'Written by ');
          return t.infoLink({
            href: 'https://github.com/forrestc'
          }, 'Forrest Cao');
        });
        return t.infoLine(function() {
          t.build('span', 'Not yet part of ');
          return t.infoLink({
            href: 'http://todomvc.com'
          }, 'TodoMVC');
        });
      });
    });
  });
});

export default Todo;
